//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ysnSinavOtomasyon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sinavdbEntities : DbContext
    {
        public sinavdbEntities()
            : base("name=sinavdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Derslik> Derslik { get; set; }
        public DbSet<Ogrenci> Ogrenci { get; set; }
        public DbSet<Sinav> Sinav { get; set; }
        public DbSet<SinavListe> SinavListe { get; set; }
    }
}
